set "DIRTARGET=Files Release"
set "DIRBACKEND=C:\Data\Peernet\Backend"
set "DIRBROWSER=C:\Data\Peernet\Browser\Peernet.Browser.WPF\bin\Release\net6.0-windows\win-x64\publish\"
set "DIRPLUGINS=C:\Data\Peernet\BrowserPlugins"
set "DIRPLUGINS2=C:\Data\Peernet\PluginsPrivate"

REM Backend

del "%DIRTARGET%\Backend.exe"
copy "%DIRBACKEND%\Backend.exe" "%DIRTARGET%\Backend.exe"

REM Browser

del "%DIRTARGET%\Application.dll"
del "%DIRTARGET%\AsyncAwaitBestPractices.dll"
del "%DIRTARGET%\AsyncAwaitBestPractices.MVVM.dll"
del "%DIRTARGET%\DevExpress.CodeParser.v21.2.dll"
del "%DIRTARGET%\DevExpress.Data.Desktop.v21.2.dll"
del "%DIRTARGET%\DevExpress.Data.v21.2.dll"
del "%DIRTARGET%\DevExpress.DataAccess.v21.2.dll"
del "%DIRTARGET%\DevExpress.Images.v21.2.dll"
del "%DIRTARGET%\DevExpress.Mvvm.v21.2.dll"
del "%DIRTARGET%\DevExpress.Office.v21.2.Core.dll"
del "%DIRTARGET%\DevExpress.Pdf.v21.2.Core.dll"
del "%DIRTARGET%\DevExpress.Pdf.v21.2.Drawing.dll"
del "%DIRTARGET%\DevExpress.Printing.v21.2.Core.dll"
del "%DIRTARGET%\DevExpress.RichEdit.v21.2.Core.dll"
del "%DIRTARGET%\DevExpress.Xpf.Core.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpf.Docking.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpf.DocumentViewer.v21.2.Core.dll"
del "%DIRTARGET%\DevExpress.Xpf.ExpressionEditor.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpf.Grid.v21.2.Core.dll"
del "%DIRTARGET%\DevExpress.Xpf.Grid.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpf.Grid.v21.2.Extensions.dll"
del "%DIRTARGET%\DevExpress.Xpf.Layout.v21.2.Core.dll"
del "%DIRTARGET%\DevExpress.Xpf.LayoutControl.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpf.Office.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpf.Printing.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpf.Ribbon.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpf.RichEdit.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpf.Themes.Office2019Colorful.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpf.Themes.PeernetDarkTheme.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpf.Themes.PeernetLightTheme.v21.2.dll"
del "%DIRTARGET%\DevExpress.Xpo.v21.2.dll"
del "%DIRTARGET%\Infrastructure.dll"
del "%DIRTARGET%\Microsoft.Extensions.DependencyInjection.Abstractions.dll"
del "%DIRTARGET%\Microsoft.Extensions.DependencyInjection.dll"
del "%DIRTARGET%\Microsoft.Extensions.Logging.Abstractions.dll"
del "%DIRTARGET%\Microsoft.Extensions.Logging.dll"
del "%DIRTARGET%\Microsoft.Extensions.Options.dll"
del "%DIRTARGET%\Microsoft.Extensions.Primitives.dll"
del "%DIRTARGET%\Newtonsoft.Json.dll"
del "%DIRTARGET%\Peernet Browser.deps.json"
del "%DIRTARGET%\Peernet Browser.dll"
del "%DIRTARGET%\Peernet Browser.exe"
del "%DIRTARGET%\Peernet Browser.runtimeconfig.json"
del "%DIRTARGET%\Peernet.SDK.dll"
del "%DIRTARGET%\Serilog.dll"
del "%DIRTARGET%\Serilog.Extensions.Logging.dll"
del "%DIRTARGET%\Serilog.Sinks.File.dll"
del "%DIRTARGET%\Serilog.Sinks.Trace.dll"
del "%DIRTARGET%\sni.dll"
del "%DIRTARGET%\System.Data.SqlClient.dll"
del "%DIRTARGET%\System.Private.ServiceModel.dll"
del "%DIRTARGET%\System.ServiceModel.dll"
del "%DIRTARGET%\System.ServiceModel.Http.dll"
del "%DIRTARGET%\System.ServiceModel.NetTcp.dll"
del "%DIRTARGET%\System.ServiceModel.Primitives.dll"
del "%DIRTARGET%\System.ServiceModel.Security.dll"

copy "%DIRBROWSER%\Application.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\AsyncAwaitBestPractices.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\AsyncAwaitBestPractices.MVVM.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.CodeParser.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Data.Desktop.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Data.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.DataAccess.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Images.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Mvvm.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Office.v21.2.Core.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Pdf.v21.2.Core.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Pdf.v21.2.Drawing.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Printing.v21.2.Core.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.RichEdit.v21.2.Core.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Core.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Docking.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.DocumentViewer.v21.2.Core.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.ExpressionEditor.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Grid.v21.2.Core.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Grid.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Grid.v21.2.Extensions.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Layout.v21.2.Core.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.LayoutControl.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Office.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Printing.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Ribbon.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.RichEdit.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Themes.Office2019Colorful.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Themes.PeernetDarkTheme.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpf.Themes.PeernetLightTheme.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\DevExpress.Xpo.v21.2.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Infrastructure.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Microsoft.Extensions.DependencyInjection.Abstractions.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Microsoft.Extensions.DependencyInjection.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Microsoft.Extensions.Logging.Abstractions.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Microsoft.Extensions.Logging.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Microsoft.Extensions.Options.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Microsoft.Extensions.Primitives.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Newtonsoft.Json.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Peernet Browser.deps.json" "%DIRTARGET%\"
copy "%DIRBROWSER%\Peernet Browser.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Peernet Browser.exe" "%DIRTARGET%\"
copy "%DIRBROWSER%\Peernet Browser.runtimeconfig.json" "%DIRTARGET%\"
copy "%DIRBROWSER%\Peernet.SDK.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Serilog.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Serilog.Extensions.Logging.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Serilog.Sinks.File.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\Serilog.Sinks.Trace.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\sni.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\System.Data.SqlClient.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\System.Private.ServiceModel.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\System.ServiceModel.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\System.ServiceModel.Http.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\System.ServiceModel.NetTcp.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\System.ServiceModel.Primitives.dll" "%DIRTARGET%\"
copy "%DIRBROWSER%\System.ServiceModel.Security.dll" "%DIRTARGET%\"

REM Browser Plugins

rmdir /S /Q "%DIRTARGET%\Plugins"
mkdir "%DIRTARGET%\Plugins"

xcopy "%DIRPLUGINS%\Peernet.Browser.Plugins.ImageViewer\bin\Release\net6.0-windows\publish" "%DIRTARGET%\Plugins\ImageViewer" /E /I
xcopy "%DIRPLUGINS%\Peernet.Browser.Plugins.MediaPlayer\bin\Release\net6.0-windows\publish" "%DIRTARGET%\Plugins\MediaPlayer" /E /I
xcopy "%DIRPLUGINS%\Peernet.Browser.Plugins.TextViewer\bin\Release\net6.0-windows\publish" "%DIRTARGET%\Plugins\TextViewer" /E /I
xcopy "%DIRPLUGINS%\Peernet.Browser.Plugins.ByteViewer\bin\Release\net6.0-windows\publish" "%DIRTARGET%\Plugins\ByteViewer" /E /I
xcopy "%DIRPLUGINS%\Peernet.Browser.Plugins.HTMLViewer\bin\Release\net6.0-windows\publish" "%DIRTARGET%\Plugins\HTMLViewer" /E /I

xcopy "%DIRPLUGINS2%\Peernet.Browser.Plugins.ExcelViewer\bin\Release\net6.0-windows\publish" "%DIRTARGET%\Plugins\ExcelViewer" /E /I
xcopy "%DIRPLUGINS2%\Peernet.Browser.Plugins.PDFViewer\bin\Release\net6.0-windows\publish" "%DIRTARGET%\Plugins\PDFViewer" /E /I
xcopy "%DIRPLUGINS2%\Peernet.Browser.Plugins.WordViewer\bin\Release\net6.0-windows\publish" "%DIRTARGET%\Plugins\WordViewer" /E /I

PAUSE
